using System;
using System.Collections.Generic;

namespace Prosim2GSX.Web.Contracts
{
    // Wire shape for the passenger-simulation manifest. Generated by
    // PassengerSimulationService when the user clicks SIMULATE on the
    // Aircraft Status panel; persisted in-memory for the rest of the
    // session so GET /api/passengers/manifest can re-serve it without
    // regenerating (different randomly-picked names every refresh would
    // be confusing).
    //
    // Wall-clock GeneratedAt and SeatOccupationWritten are surfaced so
    // the UI can show "manifest of N pax generated HH:MM:SS" with a
    // visual cue when the dataref write failed (e.g. SDK disconnected
    // mid-request). The actual seating-map render comes from the
    // WeightBalance "weightBalance" WebSocket channel because the dataref
    // write triggers a re-broadcast on the next tick.
    public class PassengerManifestDto
    {
        public int TotalPassengers { get; set; }
        public DateTime GeneratedAt { get; set; }
        public bool SeatOccupationWritten { get; set; }
        public List<PassengerEntryDto> Passengers { get; set; } = new();
    }

    public class PassengerEntryDto
    {
        // 1-based seat number — seats 1..24 are zone 1, 25..54 zone 2,
        // 55..90 zone 3, 91..132 zone 4 on the standard A320 layout.
        public int SeatNumber { get; set; }
        public int Zone { get; set; }
        public string FirstName { get; set; } = "";
        public string LastName { get; set; } = "";
    }

    // Body of POST /api/passengers/simulate. Count is nullable so the
    // client can omit it to mean "fill to capacity".
    public class SimulatePassengersRequest
    {
        public int? Count { get; set; }
    }

    // Result wrapper for both /simulate and /clear so the React panel
    // can show success/error toasts the same way as FMS sync.
    public class PassengerSimulationResultDto
    {
        public bool Success { get; set; }
        public string ErrorMessage { get; set; } = "";
        public PassengerManifestDto Manifest { get; set; }
    }
}
