import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Section } from "../../components/forms/Section";
import { BoolField, NumberField, SelectField } from "../../components/forms/Field";
import { REMOVE_STAIRS_OPTIONS } from "../../types";
// Mirrors the WPF "ControlGateDoors" surface: DOOR HANDLING + JETWAY &
// STAIR CONTROL — combined into one tab section as in the WPF view.
export function GateDoorsSection({ draft, update }) {
    return (_jsxs(_Fragment, { children: [_jsxs(Section, { title: "Doors", children: [_jsx(BoolField, { label: "Door Stair Handling", value: draft.doorStairHandling, onChange: (v) => update("doorStairHandling", v) }), _jsx(BoolField, { label: "Door Cargo Handling", value: draft.doorCargoHandling, onChange: (v) => update("doorCargoHandling", v) }), _jsx(BoolField, { label: "Door Catering Handling", value: draft.doorCateringHandling, onChange: (v) => update("doorCateringHandling", v) }), _jsx(BoolField, { label: "Door Open on Boarding Active", value: draft.doorOpenBoardActive, onChange: (v) => update("doorOpenBoardActive", v) }), _jsx(BoolField, { label: "Cargo Doors Keep Open on Loaded", value: draft.doorsCargoKeepOpenOnLoaded, onChange: (v) => update("doorsCargoKeepOpenOnLoaded", v) }), _jsx(BoolField, { label: "Cargo Doors Keep Open on Unloaded", value: draft.doorsCargoKeepOpenOnUnloaded, onChange: (v) => update("doorsCargoKeepOpenOnUnloaded", v) }), _jsx(BoolField, { label: "Close Doors on Final", value: draft.closeDoorsOnFinal, onChange: (v) => update("closeDoorsOnFinal", v) })] }), _jsxs(Section, { title: "Jetway / Stairs", children: [_jsx(BoolField, { label: "Call on Preparation", value: draft.callJetwayStairsOnPrep, onChange: (v) => update("callJetwayStairsOnPrep", v) }), _jsx(BoolField, { label: "Call During Departure", value: draft.callJetwayStairsDuringDeparture, onChange: (v) => update("callJetwayStairsDuringDeparture", v) }), _jsx(BoolField, { label: "Call on Arrival", value: draft.callJetwayStairsOnArrival, onChange: (v) => update("callJetwayStairsOnArrival", v) }), _jsx(SelectField, { label: "Remove Stairs After Departure", value: draft.removeStairsAfterDepature, options: REMOVE_STAIRS_OPTIONS, onChange: (v) => update("removeStairsAfterDepature", v) }), _jsx(BoolField, { label: "Remove Jetway/Stairs on Final", value: draft.removeJetwayStairsOnFinal, onChange: (v) => update("removeJetwayStairsOnFinal", v) })] })] }));
}
// Numeric field for ChockDelay etc. lives in GroundEquipmentSection per the
// WPF grouping (ground-equipment includes chocks). NumberField imported here
// only for the unused-import guard.
void NumberField;
